import Link from "next/link";
import { ArrowRight, BadgeCheck, ShieldCheck, Truck } from "lucide-react";

const featureImages = ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=85", "https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?auto=format&fit=crop&w=900&q=85", "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?auto=format&fit=crop&w=900&q=85"];

export default function Home() {
  return <main>
    <section className="hero"><div className="hero-grid" /><div className="hero-copy"><span className="mono hero-kicker">AUTHENTICITY OVER EVERYTHING</span><h1 className="display">NO CAPS</h1><p>The ultimate destination for premium, verified headwear. We curate the culture&apos;s most sought-after drops with zero compromise on quality.</p><div className="hero-actions"><Link className="button" href="/products">SHOP NOW <ArrowRight size={16} /></Link><Link className="button light" href="/products">VIEW CATALOG</Link></div></div><div className="hero-word display">STREETWEAR</div></section>
    <section className="trust-row page-width">{[[ShieldCheck, "AUTHENTICITY", "100% VERIFIED GENUINE GEAR"], [Truck, "FAST DELIVERY", "SHIPPED WITHIN 24 HOURS"], [BadgeCheck, "MONEY BACK", "30-DAY NO HASSLE RETURNS"]].map(([Icon, title, copy]) => <div key={title as string}><span className="trust-icon"><Icon size={26} /></span><h2 className="display">{title as string}</h2><p className="mono">{copy as string}</p></div>)}</section>
    <section className="brand-strip"><span className="display">TRUSTED BRANDS</span><div className="brand-window"><div className="brand-track">{[0, 1].map((group) => <div className="brand-group" aria-hidden={group === 1} key={group}>{["NIKE", "ADIDAS", "NEW ERA", "PUMA", "REEBOK", "CHAMPION"].map((brand) => <b className="display" key={`${group}-${brand}`}>{brand}</b>)}</div>)}</div></div></section>
    <section className="feature-grid page-width"><Link className="feature-main" href="/products/core-structure-cap"><img src={featureImages[0]} alt="Black cap from the core collection" /><span className="display">ELITE COLLECTION</span></Link><div className="feature-note"><span className="display">NEW ERA EXCLUSIVE</span><p>Explore the latest collaboration series featuring premium materials and iconic silhouettes.</p><Link className="mono" href="/products">EXPLORE COLLECTION <ArrowRight size={12} /></Link></div>{featureImages.slice(1).map((image, index) => <Link className="feature-small" href="/products" key={image}><img src={image} alt={index === 0 ? "White cap" : "Streetwear cap"} /><span className="mono">{index === 0 ? "NIKE" : "ADIDAS"}</span></Link>)}</section>
    <section className="newsletter"><div><span className="mono">NEWSLETTER</span><h2 className="display">STAY IN THE<br />LOOP. NO CAPS.</h2><form><input type="email" placeholder="YOUR@EMAIL.COM" /><button className="button">JOIN</button></form></div><img src="https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=1000&q=85" alt="Minimal retail store interior" /></section>
  </main>;
}
